# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Flight Tracker' do
    pod 'Alamofire', '~> 4.7'
end

target 'Flight TrackerTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'Flight TrackerUITests' do
  inherit! :search_paths
  # Pods for testing
end
